### ISSUE TITLE
1.1.4 버전 빌드 시 에러 발생

### ISSUE THREAD

**Issue by NK-Studio** [hwi-middle/UnityEZ2Screenshot#1]
![error](https://user-images.githubusercontent.com/53283888/166971102-83103b84-2ebf-46d0-9a91-2b0020524c00.png)

비어있는 프로젝트에 1.1.4버전을 넣고 빌드를 했을 때 이미지와 같은 버그가 발생합니다.

**Comment by hwi-middle** [comment]
오류를 확인하였으며, 현재 수정 중입니다. 감사합니다.

**Comment by hwi-middle** [comment]
[1.1.6 빌드](https://github.com/hwi-middle/UnityEZ2Screenshot/releases/tag/1.1.6)에서 해결되었습니다.
